// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserWithoutPassword } from "./UserWithoutPassword";

export interface GetCurrentUserResponse {
  user: UserWithoutPassword;
  message: string;
}
