// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TodoItem {
  id: string;
  title: string;
  description: string | null;
  completed: boolean;
  list_id: string;
  created_at: string;
  updated_at: string;
}
