[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.3"
bcrypt = "0.15.0"
chrono = { version = "0.4.31", features = ["serde"] }
dotenvy = "0.15.7"
jsonwebtoken = "9.2.0"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
sqlx = { version = "0.7.3", features = [
  "postgres",
  "time",
  "chrono",
  "uuid",
  "runtime-tokio",
] }
tokio = { version = "1.35.1", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.5.0", features = ["cors"] }
ts-rs = "7.1.0"
uuid = { version = "1.6.1", features = ["serde", "v4"] }
