// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TodoList {
  id: string;
  name: string;
  user_id: string;
  created_at: string;
  updated_at: string;
}
